#файлдля указани кастомных меток проекта
#при добавлении нового типа меток в тесты добавь их ниже, формат "название: описание"
[pytest]
markers =
    login_guest: mark test for login as guest
    smoke: marker for smoke tests
    regression: marker for regression tests
    need_review: marker for final task
